### PR TITLE
OC-20590-fix-security-vulnerabilities

### PR DESCRIPTION
**Pull request by rizwan-oc**

### CODE REVIEW

**Comment by gushil** [comment]
@rizwan-oc 

You've already building the kobocat image with these changes and make sure Form Designer is running fine afterwards, right?

**Comment by rizwan-oc** [comment]
> @rizwan-oc
> 
> You've already building the kobocat image with these changes and make sure Form Designer is running fine afterwards, right?

@gushil yes you are right I am able to build the kobocat image with these changes and yes form designer is running fine with these changes.

**Comment by gushil** [comment]
> > @rizwan-oc
> > You've already building the kobocat image with these changes and make sure Form Designer is running fine afterwards, right?
> 
> @gushil yes you are right I am able to build the kobocat image with these changes and yes form designer is running fine with these changes.

Great!

**Review by gushil — APPROVED** [review]

**Review by jmcinerney — APPROVED** [review]
👍

**Pull request merged**
